from app.models import db, Favorite


def seed_favorites():
    num1 = Favorite(user_id=1, venue_id=1)
    num2 = Favorite(user_id=1, venue_id=2)
    num3 = Favorite(user_id=1, venue_id=3)
    num4 = Favorite(user_id=2, venue_id=4)
    num5 = Favorite(user_id=2, venue_id=5)
    num6 = Favorite(user_id=3, venue_id=6)
    num7 = Favorite(user_id=3, venue_id=7)
    num8 = Favorite(user_id=4, venue_id=8)
    num9 = Favorite(user_id=4, venue_id=9)
    num10 = Favorite(user_id=5, venue_id=1)
    num11 = Favorite(user_id=5, venue_id=2)
    num12 = Favorite(user_id=6, venue_id=3)
    num13 = Favorite(user_id=6, venue_id=4)
    num14 = Favorite(user_id=7, venue_id=5)
    num15 = Favorite(user_id=8, venue_id=6)
    num16 = Favorite(user_id=8, venue_id=7)
    num17 = Favorite(user_id=9, venue_id=8)
    num18 = Favorite(user_id=9, venue_id=9)
    num19 = Favorite(user_id=10, venue_id=10)
    num20 = Favorite(user_id=10, venue_id=11)
    num21 = Favorite(user_id=11, venue_id=12)
    num22 = Favorite(user_id=11, venue_id=13)
    num23 = Favorite(user_id=12, venue_id=14)
    num24 = Favorite(user_id=12, venue_id=15)
    num25 = Favorite(user_id=13, venue_id=16)
    num26 = Favorite(user_id=13, venue_id=17)
    num27 = Favorite(user_id=14, venue_id=18)
    num28 = Favorite(user_id=14, venue_id=19)
    num29 = Favorite(user_id=15, venue_id=20)
    num30 = Favorite(user_id=15, venue_id=21)
    num31 = Favorite(user_id=16, venue_id=22)
    num32 = Favorite(user_id=16, venue_id=23)
    num33 = Favorite(user_id=17, venue_id=24)
    num34 = Favorite(user_id=17, venue_id=25)
    num35 = Favorite(user_id=18, venue_id=26)
    num36 = Favorite(user_id=18, venue_id=1)
    num37 = Favorite(user_id=19, venue_id=2)
    num38 = Favorite(user_id=19, venue_id=3)
    num39 = Favorite(user_id=20, venue_id=4)
    num40 = Favorite(user_id=20, venue_id=5)
    num41 = Favorite(user_id=21, venue_id=6)
    num42 = Favorite(user_id=21, venue_id=7)
    num43 = Favorite(user_id=22, venue_id=8)
    num44 = Favorite(user_id=22, venue_id=9)
    num45 = Favorite(user_id=23, venue_id=10)
    num46 = Favorite(user_id=23, venue_id=11)
    num47 = Favorite(user_id=24, venue_id=12)
    num48 = Favorite(user_id=24, venue_id=13)
    num49 = Favorite(user_id=25, venue_id=14)
    num50 = Favorite(user_id=25, venue_id=15)
    num51 = Favorite(user_id=26, venue_id=16)
    num52 = Favorite(user_id=26, venue_id=17)
    num53 = Favorite(user_id=27, venue_id=18)
    num54 = Favorite(user_id=27, venue_id=19)
    num55 = Favorite(user_id=28, venue_id=20)
    num56 = Favorite(user_id=28, venue_id=21)
    num57 = Favorite(user_id=29, venue_id=22)
    num58 = Favorite(user_id=29, venue_id=23)
    num59 = Favorite(user_id=30, venue_id=24)
    num60 = Favorite(user_id=30, venue_id=25)
    num61 = Favorite(user_id=31, venue_id=26)
    num62 = Favorite(user_id=31, venue_id=1)
    num63 = Favorite(user_id=32, venue_id=2)
    num64 = Favorite(user_id=32, venue_id=3)
    num65 = Favorite(user_id=33, venue_id=4)
    num66 = Favorite(user_id=33, venue_id=5)
    num67 = Favorite(user_id=34, venue_id=6)

    db.session.add(num1)
    db.session.add(num2)
    db.session.add(num3)
    db.session.add(num4)
    db.session.add(num5)
    db.session.add(num6)
    db.session.add(num7)
    db.session.add(num8)
    db.session.add(num9)
    db.session.add(num10)
    db.session.add(num11)
    db.session.add(num12)
    db.session.add(num13)
    db.session.add(num14)
    db.session.add(num15)
    db.session.add(num16)
    db.session.add(num17)
    db.session.add(num18)
    db.session.add(num19)
    db.session.add(num20)
    db.session.add(num21)
    db.session.add(num22)
    db.session.add(num23)
    db.session.add(num24)
    db.session.add(num25)
    db.session.add(num26)
    db.session.add(num27)
    db.session.add(num28)
    db.session.add(num29)
    db.session.add(num30)
    db.session.add(num31)
    db.session.add(num32)
    db.session.add(num33)
    db.session.add(num34)
    db.session.add(num35)
    db.session.add(num36)
    db.session.add(num37)
    db.session.add(num38)
    db.session.add(num39)
    db.session.add(num40)
    db.session.add(num41)
    db.session.add(num42)
    db.session.add(num43)
    db.session.add(num44)
    db.session.add(num45)
    db.session.add(num46)
    db.session.add(num47)
    db.session.add(num48)
    db.session.add(num49)
    db.session.add(num50)
    db.session.add(num51)
    db.session.add(num52)
    db.session.add(num53)
    db.session.add(num54)
    db.session.add(num55)
    db.session.add(num56)
    db.session.add(num57)
    db.session.add(num58)
    db.session.add(num59)
    db.session.add(num60)
    db.session.add(num61)
    db.session.add(num62)
    db.session.add(num63)
    db.session.add(num64)
    db.session.add(num65)
    db.session.add(num66)
    db.session.add(num67)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_favorites():
    db.session.execute('TRUNCATE favorites RESTART IDENTITY CASCADE;')
    db.session.commit()
