from app.models import db, Favorite


def seed_favorites():
    num1 = Favorite(user_id=1, venue_id=1)
    # 2 = Favorite(user_id=1, venue_id=2)
    # 3 = Favorite(user_id=1, venue_id=3)
    # 4 = Favorite(user_id=2, venue_id=4)
    # 5 = Favorite(user_id=2, venue_id=5)
    # 6 = Favorite(user_id=3, venue_id=6)
    # 7 = Favorite(user_id=3, venue_id=7)
    # 8 = Favorite(user_id=4, venue_id=8)
    # 9 = Favorite(user_id=4, venue_id=9)
    # 10 = Favorite(user_id=5, venue_id=1)
    # 11 = Favorite(user_id=5, venue_id=2)
    # 12 = Favorite(user_id=6, venue_id=3)
    # 13 = Favorite(user_id=6, venue_id=4)
    # 14 = Favorite(user_id=7, venue_id=5)
    # 15 = Favorite(user_id=8, venue_id=6)
    # 16 = Favorite(user_id=8, venue_id=7)
    # 17 = Favorite(user_id=9, venue_id=8)
    # 18 = Favorite(user_id=9, venue_id=9)
    # 19 = Favorite(user_id=10, venue_id=10)
    # 20 = Favorite(user_id=10, venue_id=11)
    # 21 = Favorite(user_id=11, venue_id=12)
    # 22 = Favorite(user_id=11, venue_id=13)
    # 23 = Favorite(user_id=12, venue_id=14)
    # 24 = Favorite(user_id=12, venue_id=15)
    # 25 = Favorite(user_id=13, venue_id=16)
    # 26 = Favorite(user_id=13, venue_id=17)
    # 27 = Favorite(user_id=14, venue_id=18)
    # 28 = Favorite(user_id=14, venue_id=19)
    # 29 = Favorite(user_id=15, venue_id=20)
    # 30 = Favorite(user_id=15, venue_id=21)
    # 31 = Favorite(user_id=16, venue_id=22)
    # 32 = Favorite(user_id=16, venue_id=23)
    # 33 = Favorite(user_id=17, venue_id=24)
    # 34 = Favorite(user_id=17, venue_id=25)
    # 35 = Favorite(user_id=18, venue_id=26)
    # 36 = Favorite(user_id=18, venue_id=1)
    # 37 = Favorite(user_id=19, venue_id=2)
    # 38 = Favorite(user_id=19, venue_id=3)
    # 39 = Favorite(user_id=20, venue_id=4)
    # 40 = Favorite(user_id=20, venue_id=5)
    # 41 = Favorite(user_id=21, venue_id=6)
    # 42 = Favorite(user_id=21, venue_id=7)
    # 43 = Favorite(user_id=22, venue_id=8)
    # 44 = Favorite(user_id=22, venue_id=9)
    # 45 = Favorite(user_id=23, venue_id=10)
    # 46 = Favorite(user_id=23, venue_id=11)
    # 47 = Favorite(user_id=24, venue_id=12)
    # 48 = Favorite(user_id=24, venue_id=13)
    # 49 = Favorite(user_id=25, venue_id=14)
    # 50 = Favorite(user_id=25, venue_id=15)
    # 51 = Favorite(user_id=26, venue_id=16)
    # 52 = Favorite(user_id=26, venue_id=17)
    # 53 = Favorite(user_id=27, venue_id=18)
    # 54 = Favorite(user_id=27, venue_id=19)
    # 55 = Favorite(user_id=28, venue_id=20)
    # 56 = Favorite(user_id=28, venue_id=21)
    # 57 = Favorite(user_id=29, venue_id=22)
    # 58 = Favorite(user_id=29, venue_id=23)
    # 59 = Favorite(user_id=30, venue_id=24)
    # 60 = Favorite(user_id=30, venue_id=25)
    # 61 = Favorite(user_id=31, venue_id=26)
    # 62 = Favorite(user_id=31, venue_id=1)
    # 63 = Favorite(user_id=32, venue_id=2)
    # 64 = Favorite(user_id=32, venue_id=3)
    # 65 = Favorite(user_id=33, venue_id=4)
    # 66 = Favorite(user_id=33, venue_id=5)
    # 67 = Favorite(user_id=34, venue_id=6)

    db.session.add(num1)
    # db.session.add(2)
    # db.session.add(3)
    # db.session.add(4)
    # db.session.add(5)
    # db.session.add(6)
    # db.session.add(7)
    # db.session.add(8)
    # db.session.add(9)
    # db.session.add(10)
    # db.session.add(11)
    # db.session.add(12)
    # db.session.add(13)
    # db.session.add(14)
    # db.session.add(15)
    # db.session.add(16)
    # db.session.add(17)
    # db.session.add(18)
    # db.session.add(19)
    # db.session.add(20)
    # db.session.add(21)
    # db.session.add(22)
    # db.session.add(23)
    # db.session.add(24)
    # db.session.add(25)
    # db.session.add(26)
    # db.session.add(27)
    # db.session.add(28)
    # db.session.add(29)
    # db.session.add(30)
    # db.session.add(31)
    # db.session.add(32)
    # db.session.add(33)
    # db.session.add(34)
    # db.session.add(35)
    # db.session.add(36)
    # db.session.add(37)
    # db.session.add(38)
    # db.session.add(39)
    # db.session.add(40)
    # db.session.add(41)
    # db.session.add(42)
    # db.session.add(43)
    # db.session.add(44)
    # db.session.add(45)
    # db.session.add(46)
    # db.session.add(47)
    # db.session.add(48)
    # db.session.add(49)
    # db.session.add(50)
    # db.session.add(51)
    # db.session.add(52)
    # db.session.add(53)
    # db.session.add(54)
    # db.session.add(55)
    # db.session.add(56)
    # db.session.add(57)
    # db.session.add(58)
    # db.session.add(59)
    # db.session.add(60)
    # db.session.add(61)
    # db.session.add(62)
    # db.session.add(63)
    # db.session.add(64)
    # db.session.add(65)
    # db.session.add(66)
    # db.session.add(67)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_favorites():
    db.session.execute('TRUNCATE favorites RESTART IDENTITY CASCADE;')
    db.session.commit()
